version: '3.8'

services:
  client:
    depends_on:
      - server
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    container_name: link_vault_frontend
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - '3000:3000'
    working_dir: /app
    stdin_open: true

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: link_vault-backend
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - '8000:8000'

  remitflex-server:
    build:
      context: ./
      dockerfile: ./remitflex/backend/Dockerfile
    container_name: remitflex-backend
    volumes:
      - "./remitflex/backend:/app"
      - "/app/node_modules"
    ports:
      - '3001:3001'

  remitflex-client:
    depends_on:
      - remitflex-server
    build:
      context: ./
      dockerfile: ./remitflex/frontend/Dockerfile
    container_name: remitflex-frontend
    volumes:
      - "./remitflex/frontend:/app"
      - "/app/node_modules"
    ports:
      - '8001:8001'
    working_dir: /app
    stdin_open: true
